name: familytree
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.3+3
environment:
  sdk: ^3.5.3

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.15
  http: ^1.2.2
  loading_animation_widget: ^1.3.0
  riverpod_annotation: ^2.6.1
  google_fonts: ^6.2.1
  riverpod_generator: ^2.6.3
  intl_phone_field: ^3.2.0
  pin_code_fields: ^8.0.1
  file_picker: ^10.1.9
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  url_launcher: ^6.2.5
  youtube_player_iframe: ^5.2.1
  sidebarx: ^0.17.1
  flutter_advanced_drawer: ^1.3.7
  share_plus: ^11.0.0
  screenshot: ^3.0.0
  qr_flutter: ^4.1.0
  permission_handler: ^12.0.0+1

  image_picker: ^1.1.2
  dropdown_button2: ^2.3.9
  contact_add: ^0.0.3
  record: ^6.0.0
  emoji_picker_flutter: ^4.3.0 

  flutter_dotenv: ^5.2.1
  image: ^4.3.0
  dotted_border: ^2.1.0
  font_awesome_flutter: ^10.8.0
  socket_io_client: ^3.1.2

  keyboard_avoider: ^0.2.0
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  flutter_local_notifications: ^19.3.0
  firebase_messaging: ^15.1.6
  flutter_upgrade_version: ^1.1.7
  multi_select_flutter: ^4.1.3
  image_gallery_saver_plus: ^4.0.1
  flutter_launcher_icons: ^0.14.4

  custom_image_crop: ^0.1.1
  path_provider: ^2.1.2
  webview_flutter: ^4.7.0
  mobile_scanner: ^6.0.7
  auto_size_text: ^3.0.0
  app_links: ^6.4.0
  rename_app: ^1.6.5
  excel: ^4.0.6
  flutter_secure_storage: ^9.2.4
  razorpay_flutter: ^1.4.0
  flutter_mosaic: ^0.0.4
  dio: ^5.4.0
  dropdown_search: ^6.0.2
  shared_preferences: ^2.5.3
  flutter_inappwebview: ^6.0.0
  youtube_player_flutter: ^9.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.6

flutter:
  uses-material-design: true
  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica.ttf
          weight: 400
  assets:
    - assets/
    - assets/svg/icons/
    - assets/svg/images/
    - assets/pngs/
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/pngs/familytree_logo.png"